import { createElement } from '@lwc/engine-dom';
import CaseSlaWidget from 'c/caseSlaWidget';

describe('c-case-sla-widget', () => {
    afterEach(() => {

        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {

        const element = createElement('c-case-sla-widget', {
            is: CaseSlaWidget
        });


        document.body.appendChild(element);


        expect(1).toBe(1);
    });
});